export interface LegacyVoterRecord {
  id: string;
  epicNo: string;
  fullName: string;
  relativeName: string;
  relationType: 'FATHER' | 'HUSBAND' | 'MOTHER' | 'OTHER';
  age: number;
  gender: 'M' | 'F' | 'O';
  partNo: string;
  sectionNo: string;
  serialNo: number;
  address: string;
  soundexName: string;
  metaphoneName: string;
  soundexRelative: string;
}

export const INITIAL_LEGACY_SNAPSHOT_2002_04: Omit<LegacyVoterRecord, 'soundexName' | 'metaphoneName' | 'soundexRelative'>[] = [
  {
    id: 'LEG-001',
    epicNo: 'XYZ1029384',
    fullName: 'Ramesh Kumar Sharma',
    relativeName: 'Dwarka Prasad Sharma',
    relationType: 'FATHER',
    age: 48,
    gender: 'M',
    partNo: '142-Rampur',
    sectionNo: '01',
    serialNo: 12,
    address: 'House 44, Purana Chowk, Rampur',
  },
  {
    id: 'LEG-002',
    epicNo: 'XYZ1029385',
    fullName: 'Sunita Sharma',
    relativeName: 'Ramesh Kumar Sharma',
    relationType: 'HUSBAND',
    age: 44,
    gender: 'F',
    partNo: '142-Rampur',
    sectionNo: '01',
    serialNo: 13,
    address: 'House 44, Purana Chowk, Rampur',
  },
  {
    id: 'LEG-003',
    epicNo: 'ABC9988771',
    fullName: 'Mohammad Afzal Khan',
    relativeName: 'Abdul Ghaffar Khan',
    relationType: 'FATHER',
    age: 52,
    gender: 'M',
    partNo: '142-Rampur',
    sectionNo: '02',
    serialNo: 45,
    address: 'B-12, Madina Colony, Ward 4',
  },
  {
    id: 'LEG-004',
    epicNo: 'ABC9988772',
    fullName: 'Nasreen Begum',
    relativeName: 'Mohammad Afzal Khan',
    relationType: 'HUSBAND',
    age: 49,
    gender: 'F',
    partNo: '142-Rampur',
    sectionNo: '02',
    serialNo: 46,
    address: 'B-12, Madina Colony, Ward 4',
  },
  {
    id: 'LEG-005',
    epicNo: 'DLH4455661',
    fullName: 'Gurpreet Singh',
    relativeName: 'Harbhajan Singh',
    relationType: 'FATHER',
    age: 41,
    gender: 'M',
    partNo: '143-Govindpur',
    sectionNo: '01',
    serialNo: 78,
    address: 'Flat 3A, GT Road, Govindpur',
  },
  {
    id: 'LEG-006',
    epicNo: 'UPX8822331',
    fullName: 'Vikramaditya Verma',
    relativeName: 'Satya Prakash Verma',
    relationType: 'FATHER',
    age: 39,
    gender: 'M',
    partNo: '143-Govindpur',
    sectionNo: '03',
    serialNo: 104,
    address: 'Village Kheri, Post Govindpur',
  },
  {
    id: 'LEG-007',
    epicNo: 'UPX8822332',
    fullName: 'Pooja Verma',
    relativeName: 'Vikramaditya Verma',
    relationType: 'HUSBAND',
    age: 35,
    gender: 'F',
    partNo: '143-Govindpur',
    sectionNo: '03',
    serialNo: 105,
    address: 'Village Kheri, Post Govindpur',
  },
  {
    id: 'LEG-008',
    epicNo: 'BRJ5566778',
    fullName: 'Anil Kumar Yadav',
    relativeName: 'Ram Sevak Yadav',
    relationType: 'FATHER',
    age: 46,
    gender: 'M',
    partNo: '144-Kalyanpur',
    sectionNo: '01',
    serialNo: 21,
    address: 'Plot 9, Yadav Basti, Kalyanpur',
  },
  {
    id: 'LEG-009',
    epicNo: 'BRJ5566779',
    fullName: 'Manju Devi',
    relativeName: 'Anil Kumar Yadav',
    relationType: 'HUSBAND',
    age: 42,
    gender: 'F',
    partNo: '144-Kalyanpur',
    sectionNo: '01',
    serialNo: 22,
    address: 'Plot 9, Yadav Basti, Kalyanpur',
  },
  {
    id: 'LEG-010',
    epicNo: 'MHX1122334',
    fullName: 'Devendra Patil',
    relativeName: 'Baburao Patil',
    relationType: 'FATHER',
    age: 55,
    gender: 'M',
    partNo: '145-ShivajiNagar',
    sectionNo: '04',
    serialNo: 89,
    address: 'Lane 2, Shivaji Nagar',
  },
  {
    id: 'LEG-011',
    epicNo: 'KRN7788990',
    fullName: 'Siddaramaiah Gowda',
    relativeName: 'Chennappa Gowda',
    relationType: 'FATHER',
    age: 58,
    gender: 'M',
    partNo: '146-Channapatna',
    sectionNo: '02',
    serialNo: 33,
    address: 'Near Old Temple, Main Road',
  },
  {
    id: 'LEG-012',
    epicNo: 'TNX3344556',
    fullName: 'Karthikeyan Subramanian',
    relativeName: 'Subramanian Natarajan',
    relationType: 'FATHER',
    age: 47,
    gender: 'M',
    partNo: '147-MaduraiSouth',
    sectionNo: '01',
    serialNo: 15,
    address: '14 West Car Street',
  },
  {
    id: 'LEG-013',
    epicNo: 'WBK9988112',
    fullName: 'Debabrata Mukherjee',
    relativeName: 'Tapan Mukherjee',
    relationType: 'FATHER',
    age: 50,
    gender: 'M',
    partNo: '148-Shyambazar',
    sectionNo: '05',
    serialNo: 62,
    address: '88/2 APC Road, Kolkata',
  },
  {
    id: 'LEG-014',
    epicNo: 'WBK9988113',
    fullName: 'Mousumi Mukherjee',
    relativeName: 'Debabrata Mukherjee',
    relationType: 'HUSBAND',
    age: 46,
    gender: 'F',
    partNo: '148-Shyambazar',
    sectionNo: '05',
    serialNo: 63,
    address: '88/2 APC Road, Kolkata',
  },
  {
    id: 'LEG-015',
    epicNo: 'RJX7766554',
    fullName: 'Surendra Singh Rathore',
    relativeName: 'Bhairon Singh Rathore',
    relationType: 'FATHER',
    age: 53,
    gender: 'M',
    partNo: '149-Amber',
    sectionNo: '01',
    serialNo: 9,
    address: 'Haveli 12, Fort Road, Amber',
  }
];
